### PR TITLE
Fix sha1 for test-trigger

### LINKED ISSUE #134: commit notification null
I am getting this error if i manually trigger the plugin from stash without this options turned on:
Omit SHA1 Hash Code
Omit Branch Name
System:
Jenkins 1609.1
Git plugin 2.3.5
Stash Jenkins Webhook plugin 2.7.0
Stash Server version 3.6.0

I am basically having 2 jobs identical, only the branches name is different:
one is "master" the other one "release"

The error from Jenkins console:

 commit notification null
00:00:00.027 [EnvInject] - Loading node environment variables.
00:00:00.037 Building remotely on ****** (automation 10xwindows) in workspace C:\jenkins\workspace\StashJobTrigger_Branch
00:00:00.090  > C:\jenkins\tools\git\bin\git.exe rev-parse --is-inside-work-tree # timeout=10
00:00:00.106 Fetching changes from the remote Git repository
00:00:00.110  > C:\jenkins\tools\git\bin\git.exe config remote.origin.url ssh://************.git # timeout=10
00:00:00.130 Fetching upstream changes from ssh://*****************.git
00:00:00.132  > C:\jenkins\tools\git\bin\git.exe --version # timeout=10
00:00:00.145  > C:\jenkins\tools\git\bin\git.exe -c core.askpass=true fetch --tags --progress ssh://************.git +refs/heads/*:refs/remotes/origin/*
00:00:04.745  > C:\jenkins\tools\git\bin\git.exe rev-parse "null^{commit}" # timeout=10
00:00:04.764 FATAL: Command "C:\jenkins\tools\git\bin\git.exe rev-parse "null^{commit}"" returned status code 128:
00:00:04.764 stdout: null^{commit}
00:00:04.764 
00:00:04.764 stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
00:00:04.764 Use '--' to separate paths from revisions, like this:
00:00:04.764 'git <command> [<revision>...] -- [<file>...]'
00:00:04.764 
00:00:04.764 hudson.plugins.git.GitException: Command "C:\jenkins\tools\git\bin\git.exe rev-parse "null^{commit}"" returned status code 128:
00:00:04.765 stdout: null^{commit}
00:00:04.765 
00:00:04.765 stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
00:00:04.765 Use '--' to separate paths from revisions, like this:
00:00:04.765 'git <command> [<revision>...] -- [<file>...]'
00:00:04.765 
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1567)
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1563)
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1249)
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1261)
00:00:04.765 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:622)
00:00:04.765 	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
00:00:04.765 	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
00:00:04.765 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:04.765 	at java.lang.reflect.Method.invoke(Method.java:601)
00:00:04.765 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:299)
00:00:04.765 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:280)
00:00:04.765 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:239)
00:00:04.765 	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
00:00:04.765 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
00:00:04.765 	at hudson.remoting.Request$2.run(Request.java:328)
00:00:04.765 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
00:00:04.765 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
00:00:04.765 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
00:00:04.765 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
00:00:04.765 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
00:00:04.765 	at hudson.remoting.Engine$1$1.run(Engine.java:63)
00:00:04.765 	at java.lang.Thread.run(Thread.java:722)
00:00:04.765 	at ......remote call to oo10.x_node2(Native Method)
00:00:04.766 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
00:00:04.766 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
00:00:04.766 	at hudson.remoting.Channel.call(Channel.java:753)
00:00:04.766 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:179)
00:00:04.766 	at com.sun.proxy.$Proxy50.revParse(Unknown Source)
00:00:04.766 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.revParse(RemoteGitImpl.java:546)
00:00:04.766 	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:85)
00:00:04.766 	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:903)
00:00:04.766 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1017)
00:00:04.766 	at hudson.scm.SCM.checkout(SCM.java:484)
00:00:04.766 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
00:00:04.766 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
00:00:04.766 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:04.766 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
00:00:04.766 	at hudson.model.Run.execute(Run.java:1741)
00:00:04.766 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:537)
00:00:04.766 	at hudson.model.ResourceController.execute(ResourceController.java:98)
00:00:04.766 	at hudson.model.Executor.run(Executor.java:374)
00:00:04.772 Finished: FAILURE

### PR DESCRIPTION
**Pull request by SuperTux88**
This fixes #134

I also use the branch name of the default branch, if omitBranchName is not active.

### CODE REVIEW

File: src/main/java/com/nerdwin15/stash/webhook/Notifier.java [hunk 1]
```diff
@@ -261,7 +261,7 @@ protected String getUrl(final Repository repository, final String jenkinsBase,
 
     if(strRef != null && !omitBranchName)
       url.append(String.format(BRANCH_URL_PARAMETER, urlEncode(strRef)));
-    if(!omitHashCode)
+    if(strSha1 != null && !omitHashCode)
```
Comment (jglick) [inline src/main/java/com/nerdwin15/stash/webhook/Notifier.java]: :+1: this is necessary to avoid build failures in certain Jenkins configurations. (Git plugin 2.3.5, Workflow multibranch projects)
